// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCenD0V_d0PFEBt2rRTPrVJFZk8ysGbSOo',
    appId: '1:834450947640:web:19cd6e3c765bf540b6b0cd',
    messagingSenderId: '834450947640',
    projectId: 'safesteps-8351d',
    authDomain: 'safesteps-8351d.firebaseapp.com',
    storageBucket: 'safesteps-8351d.firebasestorage.app',
    measurementId: 'G-MLK9PFZ31H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCneWI6UCXj__cY0PoRKdQGZ-L6aSUymCY',
    appId: '1:834450947640:android:08837ce2db268c64b6b0cd',
    messagingSenderId: '834450947640',
    projectId: 'safesteps-8351d',
    storageBucket: 'safesteps-8351d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCKZ5pKSWwZrol7HiVqUxc0hf-0NRfQVI',
    appId: '1:834450947640:ios:55c02d5dc01d4c5eb6b0cd',
    messagingSenderId: '834450947640',
    projectId: 'safesteps-8351d',
    storageBucket: 'safesteps-8351d.firebasestorage.app',
    iosBundleId: 'com.safesteps.safesteps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCKZ5pKSWwZrol7HiVqUxc0hf-0NRfQVI',
    appId: '1:834450947640:ios:55c02d5dc01d4c5eb6b0cd',
    messagingSenderId: '834450947640',
    projectId: 'safesteps-8351d',
    storageBucket: 'safesteps-8351d.firebasestorage.app',
    iosBundleId: 'com.safesteps.safesteps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCenD0V_d0PFEBt2rRTPrVJFZk8ysGbSOo',
    appId: '1:834450947640:web:7f5553a2ad32bb15b6b0cd',
    messagingSenderId: '834450947640',
    projectId: 'safesteps-8351d',
    authDomain: 'safesteps-8351d.firebaseapp.com',
    storageBucket: 'safesteps-8351d.firebasestorage.app',
    measurementId: 'G-39KDPKKNJY',
  );
}
